'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { readJsonFile, writeJsonFile } = require('./fs-utils.cjs');

const HOOK_EVENTS = new Set(['PreToolUse', 'PostToolUse', 'UserPromptSubmit', 'SessionStart']);
const CLEAN_ROOM_HOOK_TIMEOUT_SECONDS = 30;
const OPENCODE_PLUGIN_MARKER = 'clean-room-skill-opencode-plugin-v1';

const CLEAN_ROOM_HOOKS = [
  {
    event: 'PreToolUse',
    matcher: 'Bash|Shell|PowerShell|Monitor|exec_command|shell_command|write_stdin',
    checks: ['require-clean-room-env.py', 'deny-clean-room-shell.py'],
  },
  {
    event: 'PreToolUse',
    matcher: 'Read|Glob|Grep|LS|LSP|NotebookRead|view_image|list_dir|ListMcpResourcesTool|ReadMcpResourceTool|ListMcpResourceTemplatesTool|list_mcp_resources|list_mcp_resource_templates|read_mcp_resource',
    checks: ['require-clean-room-env.py', 'deny-clean-source-read.py'],
  },
  {
    event: 'PreToolUse',
    matcher: 'Write|Edit|MultiEdit|NotebookEdit|apply_patch',
    checks: ['require-clean-room-env.py', 'deny-contaminated-clean-write.py'],
  },
  {
    event: 'PostToolUse',
    matcher: 'Write|Edit|MultiEdit|NotebookEdit|apply_patch',
    checks: [
      'require-clean-room-env.py',
      'check-artifact-leakage.py',
      'validate-json-schema.py',
      'validate-handoff-package.py',
    ],
  },
];

function shellQuote(value) {
  const text = String(value);
  if (text === '') {
    return "''";
  }
  return `'${text.replace(/'/g, "'\"'\"'")}'`;
}

function buildHookCommand({ pythonPath, wrapperPath, mode, checks }) {
  const parts = [
    shellQuote(pythonPath),
    shellQuote(wrapperPath),
    '--mode',
    mode,
  ];
  for (const check of checks) {
    parts.push('--check', check);
  }
  return parts.join(' ');
}

function buildHookEntries({ pythonPath, wrapperPath, mode }) {
  return CLEAN_ROOM_HOOKS.map((entry) => ({
    event: entry.event,
    matcher: entry.matcher,
    hook: {
      type: 'command',
      command: buildHookCommand({
        pythonPath,
        wrapperPath,
        mode,
        checks: entry.checks,
      }),
      timeout: CLEAN_ROOM_HOOK_TIMEOUT_SECONDS,
      statusMessage: 'Checking clean-room guardrails',
    },
  }));
}

function isManagedHook(hook) {
  return !!(
    hook &&
    typeof hook === 'object' &&
    typeof hook.command === 'string' &&
    hook.command.includes('clean-room-hook.py')
  );
}

function hasTopLevelHookEvents(value) {
  return Object.keys(value || {}).some((key) => HOOK_EVENTS.has(key));
}

function hookTableFor(value) {
  if (value && typeof value.hooks === 'object' && value.hooks !== null && !Array.isArray(value.hooks)) {
    return value.hooks;
  }
  if (hasTopLevelHookEvents(value)) {
    return value;
  }
  return null;
}

function ensureHookTable(value) {
  const table = hookTableFor(value);
  if (table) {
    return table;
  }
  value.hooks = {};
  return value.hooks;
}

function removeManagedHookEntriesFromTable(table) {
  // Preserve user hooks. Only remove entries generated by this installer wrapper.
  let changed = false;
  for (const event of Object.keys(table)) {
    if (!Array.isArray(table[event])) {
      continue;
    }
    const nextEntries = [];
    for (const entry of table[event]) {
      if (!entry || typeof entry !== 'object' || !Array.isArray(entry.hooks)) {
        nextEntries.push(entry);
        continue;
      }
      const hooks = entry.hooks.filter((hook) => !isManagedHook(hook));
      if (hooks.length !== entry.hooks.length) {
        changed = true;
      }
      if (hooks.length > 0) {
        nextEntries.push({ ...entry, hooks });
      } else {
        changed = true;
      }
    }
    if (nextEntries.length > 0) {
      table[event] = nextEntries;
    } else {
      delete table[event];
    }
  }
  return changed;
}

function hasManagedHookEntries(configPath) {
  if (!fs.existsSync(configPath)) {
    return false;
  }
  const original = readJsonFile(configPath, {});
  if (!original || typeof original !== 'object' || Array.isArray(original)) {
    throw new Error(`${configPath} must contain a JSON object`);
  }
  const table = hookTableFor(original);
  if (!table) {
    return false;
  }
  for (const entries of Object.values(table)) {
    if (!Array.isArray(entries)) continue;
    for (const entry of entries) {
      if (!entry || typeof entry !== 'object' || !Array.isArray(entry.hooks)) continue;
      if (entry.hooks.some((hook) => isManagedHook(hook))) {
        return true;
      }
    }
  }
  return false;
}

function pluginPathForRuntime(runtime, targetRoot) {
  if (runtime === 'opencode') {
    return path.join(targetRoot, 'plugins', 'clean-room.ts');
  }
  return null;
}

function hasManagedOpenCodePlugin(pluginPath) {
  if (!pluginPath || !fs.existsSync(pluginPath)) {
    return false;
  }
  return fs.readFileSync(pluginPath, 'utf8').includes(OPENCODE_PLUGIN_MARKER);
}

function mergedHookConfig(configPath, entries) {
  const original = readJsonFile(configPath, {});
  if (!original || typeof original !== 'object' || Array.isArray(original)) {
    throw new Error(`${configPath} must contain a JSON object`);
  }
  const next = structuredClone(original);
  const table = ensureHookTable(next);
  removeManagedHookEntriesFromTable(table);
  for (const entry of entries) {
    if (!Array.isArray(table[entry.event])) {
      table[entry.event] = [];
    }
    table[entry.event].push({
      matcher: entry.matcher,
      hooks: [entry.hook],
    });
  }
  return next;
}

function mergeHookEntries(configPath, entries, options = {}) {
  const next = mergedHookConfig(configPath, entries);
  if (!options.dryRun) {
    writeJsonFile(configPath, next);
  }
  return next;
}

function writeHookConfig(configPath, config) {
  writeJsonFile(configPath, config);
}

function removeHookEntries(configPath, options = {}) {
  if (!fs.existsSync(configPath)) {
    return null;
  }
  const original = readJsonFile(configPath, {});
  if (!original || typeof original !== 'object' || Array.isArray(original)) {
    throw new Error(`${configPath} must contain a JSON object`);
  }
  const next = structuredClone(original);
  const table = hookTableFor(next);
  if (!table) {
    return original;
  }
  const changed = removeManagedHookEntriesFromTable(table);
  if (changed && !options.dryRun) {
    writeJsonFile(configPath, next);
  }
  return changed ? next : original;
}

function configPathForRuntime(runtime, targetRoot) {
  if (runtime === 'codex') {
    return path.join(targetRoot, 'hooks.json');
  }
  if (runtime === 'claude') {
    return path.join(targetRoot, 'settings.json');
  }
  return null;
}

module.exports = {
  buildHookEntries,
  CLEAN_ROOM_HOOKS,
  CLEAN_ROOM_HOOK_TIMEOUT_SECONDS,
  configPathForRuntime,
  hasManagedHookEntries,
  hasManagedOpenCodePlugin,
  OPENCODE_PLUGIN_MARKER,
  pluginPathForRuntime,
  removeHookEntries,
  mergeHookEntries,
  shellQuote,
  writeHookConfig,
};
